apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "haveged.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "haveged.name" . }}
  #   chart: {{ template "haveged.chart" . }}
  #   release: {{ .Release.Name }}
  #   # heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      daemonset: {{ template "haveged.name" . }}
  template:
    metadata:
      labels:
        daemonset: {{ template "haveged.name" . }}
        # app: {{ template "haveged.name" . }}
        # chart: {{ template "haveged.chart" . }}
        # release: {{ .Release.Name }}
        # # heritage: {{ .Release.Service }}
    spec:
      # selector:
      #   matchLabels:
      #     app: {{ template "haveged.name" . }}
      #     # chart: {{ template "haveged.chart" . }}
      #     # release: {{ .Release.Name }}
      #     # heritage: {{ .Release.Service }}
      containers:
        - name: {{ template "haveged.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
